name: The Cat Got Fat
favicon: null
layout_spectrum: 0.8083673701621592
typography_spectrum: 0.29992520343512297
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5082114620599896
  lightness: 0.5908651547506452
  saturation: 0.7589249366428703
  rhythmicContrast: 0.7478707134723663
purpose: []
